baseurl = "https://mohebbat.eu.org"
title = "mohebbat"
layoutDir = "layouts"
contentdir = "content"
assetDir = "static"
publishdir = "dist"
metaDataFormat = "yaml"
buildDrafts = false
buildFuture = true
canonifyurls = true
pygmentsUseClasses = true
relativeURLs = true
uglyURLs = false
verbose = false
log = false
pluralizelisttitles = false
preserveTaxonomyNames = true
footnotereturnlinkcontents = "⇆"
disableHugoGeneratorInject = true
enableRobotsTXT = true
paginatePath = "page"
enableGitInfo = true
rssLimit = 100
optimize = true
shamsiDateFormat = "d MMM ماه yyyy"
DefaultContentLanguage = "fa"

[params]
LatinName = "mohebbat"
color = "Blue"
copyright = "کلیه مطالب این وبلاگ براساس گواهی کریتیو کامنز ۴.۰ (BY-NC-SA) منتشر می‌شود. اسپانسر khiar.net"
cover = "/uploads/cover-default.png"
description = "Params description"
fullPersianName = "محبت - استاد"
htmlDirection = "rtl"
languageCode = "fa-IR"
pageCover = "/uploads/page-default.png"
paginate = 6
tags = "mohebbat, محبت"

[params.author]
email = "admin@mohebbat.eu.org"
name = "mohebbat.eu.org"

[params.link]
comment = "true"
disqusUser = "mohebbat.eu.org"
facebooUser = "mohebbat.eu.org"
facebook = "false"
github = "true"
githubUser = "0x187"
instagram = "false"
instagramUser = "mohebbat.eu.org"
rss = "true"
telegram = "true"
telegramUser = "mohebbat.eu.org"
twitter = "true"
twitterUser = "mohebbat.eu.org"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[permalinks]
feed = "/feed/:year/:month/:day"
posts = "/posts/:title/"

[taxonomies]
author = "author"
category = "section"
tag = "topic"

[mediaTypes]

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats]

[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputs]
home = ["HTML", "RSS", "AMP", "HEADERS"]
page = ["HTML", "AMP"]
section = ["HTML", "AMP"]
taxonomy = ["HTML", "AMP"]
taxonomyTerm = ["HTML", "AMP"]